version: 2
defaults: &defaults
  docker:
    - image: google/cloud-sdk@sha256:126a49cfa2aa6e20d561fa14999bf657bc341efeba04939bd2f612bf843d12a6
jobs:
  check-changes:
    docker:
        - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
              .circleci/commit_check.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - check-changes
      - approve_deploy:
          filters:
            branches:
              only: main