version: 2
defaults: &defaults
  docker:
    - image: google/cloud-sdk@sha256:126a49cfa2aa6e20d561fa14999bf657bc341efeba04939bd2f612bf843d12a6
jobs:
  check-changes:
    docker:
        - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
              .circleci/commit_check.sh

  build:
      <<: *defaults
      steps:
        - run:
            name: Install utils
            command: |
                .circleci/build.sh

  deploy:
      <<: *defaults
      steps:
        - run:
            name: Install utils
            command: |
                .circleci/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - check-changes
      - build:
          requires:
            - check-changes
      - approve_deploy:
          type: approval
          requires:
            - check-changes    
      - deploy:
          requires:
            - approve_deploy