version: 2
orbs:
  slack: circleci/slack@4.1
  
defaults:

- &tag /.*\/(prod-|stg-|qa-)\d{8}.\d{2}$/

- &tag_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: *tag

docker:
    - image: google/cloud-sdk@sha256:126a49cfa2aa6e20d561fa14999bf657bc341efeba04939bd2f612bf843d12a6
jobs:
  build_and_test:  
    docker:
        - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Execute Tests
          command: |
               chmod +x .circleci/common.sh && .circleci/common.sh
               .circleci/run_test.sh              

  deploy:
    docker:
        - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy Resources Kubernetes
          command: |
               chmod +x .circleci/deploy.sh && .circleci/deploy.sh
      - slack/notify:
          color: '#42E2F4'
          title: STARTED Dott Deployment
          message: ':grau: ${APP}/${TAG}'
          author_name: '${CIRCLE_USERNAME}'
          include_project_field: false
          include_job_number_field: false
          webhook: https://hooks.slack.com/services/${SLACK_WEBHOOK}
      - slack/notify:
          color: '#1CBF43'
          title: SUCCESS Dott Deployment
          message: ':rocket: ${APP}/${TAG}'
          author_name: '${CIRCLE_USERNAME}'
          include_project_field: false
          include_job_number_field: false
          webhook: https://hooks.slack.com/services/${SLACK_WEBHOOK}
      - slack/status:
          fail_only: true
          failure_message: ':shit: Deployment Failed!  ${APP}/${TAG}  -  Author Name: ${CIRCLE_USERNAME}'
          include_job_number_field: false
          include_project_field: false
          webhook: https://hooks.slack.com/services/${SLACK_WEBHOOK}               
               
  rollback:
    docker:
        - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
               chmod +x .circleci/rollback.sh && .circleci/rollback.sh
                                
workflows:
  version: 2
  deployment:
    jobs:
      - build_and_test:
          <<: *tag_only   
      - approve_deploy:
          type: approval
          requires:
            - build_and_test
          <<: *tag_only          
      - deploy:
          requires:
            - approve_deploy
          <<: *tag_only                  
      - approve_rollback:
          type: approval
          requires:
            - deploy
          <<: *tag_only
      - rollback:
          requires:
            - approve_rollback
          <<: *tag_only