version: 2

defaults: &defaults

# - &tag /.*\/(prod-|stg-)\d{8}.\d{2}$/

# - &tag_only
#   filters:
#     branches:
#       ignore: /.*/
#     tags:
#       only: *tag

docker:
    - image: google/cloud-sdk@sha256:126a49cfa2aa6e20d561fa14999bf657bc341efeba04939bd2f612bf843d12a6
jobs:
  build_and_test:  
    docker:
        - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Execute Tests
          command: |
               chmod +x .circleci/common.sh && .circleci/common.sh
               .circleci/run_test.sh

  deploy:
    docker:
        - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
               chmod +x .circleci/deploy.sh && .circleci/deploy.sh
               
  rollback:
    docker:
        - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
               chmod +x .circleci/rollback.sh && .circleci/rollback.sh
                                
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: main
  # deployment:
  #   jobs:
  #     - build_and_test:
  #         filters:     
  #           tags:
  #             only:  /^config-test/     
  #     - approve_deploy:
  #         type: approval
  #         requires:
  #           - build_and_test
  #         filters:     
  #           tags:
  #             only:  /^config-test/          
  #     - deploy:
  #         requires:
  #           - approve_deploy
  #         filters:     
  #           tags:
  #             only:  /^config-test/                
  #     - approve_rollback:
  #         type: approval
  #         requires:
  #           - deploy
  #         filters:     
  #           tags:
  #             only:  /^config-test/           
  #     - rollback:
  #         requires:
  #           - approve_rollback