apiVersion: v1
kind: Namespace
metadata:
  name: hello-app
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app-v1
  namespace: hello-app-v1
  labels:
    app: hello-app-v1
spec:
  selector:
    app: hello-app-v1
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-v1
  namespace: hello-app-v1
  labels:
    app: hello-app-v1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: hello-app-v1
  template:
    metadata:
      labels:
        app: hello-app-v1
    spec:
      containers:
      - name: hello-app-v1
        image: DOCKER_IMAGE_NAME
        ports:
        - containerPort: 8080